INSERT INTO region(codigo_region, nombre_region)VALUES (1, 'Región de Tarapacá')
INSERT INTO region(codigo_region, nombre_region)VALUES (2, 'Región de Antofagasta')
INSERT INTO region(codigo_region, nombre_region)VALUES (3, 'Región de Atacama')
INSERT INTO region(codigo_region, nombre_region)VALUES (4, 'Región de Coquimbo')
INSERT INTO region(codigo_region, nombre_region)VALUES (5, 'Región de Valparaíso')
INSERT INTO region(codigo_region, nombre_region)VALUES (6, 'Región de Libertador Bernardo O Higgins')
INSERT INTO region(codigo_region, nombre_region)VALUES (7, 'Región de Maule')
INSERT INTO region(codigo_region, nombre_region)VALUES (8, 'Región de Bíobío')
INSERT INTO region(codigo_region, nombre_region)VALUES (9, 'Región de La Araucanía')
INSERT INTO region(codigo_region, nombre_region)VALUES (10, 'Región de Los Lagos')
INSERT INTO region(codigo_region, nombre_region)VALUES (11, 'Región de Aisén Del General Carlos Ibáñez Del Campo')
INSERT INTO region(codigo_region, nombre_region)VALUES (12, 'Región de Magallanes Y De La Antártica Chilena')
INSERT INTO region(codigo_region, nombre_region)VALUES (13, 'Región Metropolitana De Santiago')
INSERT INTO region(codigo_region, nombre_region)VALUES (14, 'Región de Los Ríos')
INSERT INTO region(codigo_region, nombre_region)VALUES (15, 'Región de Arica y Parinacota')
INSERT INTO region(codigo_region, nombre_region)VALUES (99, 'Desconocida')

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (15101, 'Arica', 15)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (15102, 'Camarones', 15)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (15201, 'Putre', 15)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (15202, 'General Lagos', 15)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (01101, 'Iquique', 1)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (01402, 'Camiña', 1)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (01403, 'Colchane', 1)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (01404, 'Huara', 1)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (01405, 'Pica', 1)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (01401, 'Pozo Almonte', 1)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (01107, 'Alto Hospicio', 1)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02101, 'Antofagasta', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02102, 'Mejillones', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02103, 'Sierra Gorda', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02104, 'Taltal', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02201, 'Calama', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02202, 'Ollagüe', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02203, 'San Pedro de Atacama', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02301, 'Tocopilla', 2)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (02302, 'María Elena',2)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03101, 'Copiapó', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03102, 'Caldera', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03103, 'Tierra Amarilla', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03201, 'Chañaral', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03202, 'Diego de Almagro', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03301, 'Vallenar', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03302, 'Alto del Carmen', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03303, 'Freirina', 3)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (03304, 'Huasco', 3)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04101, 'La Serena' ,4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04102, 'Coquimbo', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04103, 'Andacollo', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04104, 'La Higuera' ,4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04105, 'Paiguano', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04106, 'Vicuña' ,4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04201, 'Illapel', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04202, 'Canela', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04203, 'Los Vilos', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04204, 'Salamanca', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04301, 'Ovalle', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04302, 'Combarbalá', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04303, 'Monte Patria', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04304, 'Punitaqui', 4)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (04305, 'Río Hurtado', 4)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05101, 'Valparaíso', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05102, 'Casablanca' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05103, 'Concón', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05104, 'Juan Fernández', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05105, 'Puchuncaví', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05801, 'Quilpué' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05107, 'Quintero', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05804, 'Villa Alemana', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05109, 'Viña del Mar' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05201, 'Isla de Pascua' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05301, 'Los Andes', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05302, 'Calle Larga' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05303, 'Rinconada' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05304, 'San Esteban', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05401, 'La Ligua' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05402, 'Cabildo', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05403, 'Papudo' ,5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05404, 'Petorca',5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05405, 'Zapallar', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05501, 'Quillota', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05502, 'Calera', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05503, 'Hijuelas', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05504, 'La Cruz', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05802, 'Limache', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05506, 'Nogales', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05803, 'Olmué', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05601, 'San Antonio', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05602, 'Algarrobo', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05603, 'Cartagena', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05604, 'El Quisco', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05605, 'El Tabo', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05606, 'Santo Domingo', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05701, 'San Felipe', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05702, 'Catemu', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05703, 'Llaillay', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05704, 'Panquehue', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05705, 'Putaendo', 5)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (05706, 'Santa María', 5)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06101, 'Rancagua',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06102, 'Codegua',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06103, 'Coinco',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06104, 'Coltauco',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06105, 'Doñihue',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06106, 'Graneros',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06107, 'Las Cabras',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06108, 'Machalí',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06109, 'Malloa',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06110, 'Mostazal',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06111, 'Olivar',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06112, 'Peumo',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06113, 'Pichidegua',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06114, 'Quinta de Tilcoco',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06115, 'Rengo',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06116, 'Requínoa',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06117, 'San Vicente',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06201, 'Pichilemu',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06202, 'La Estrella',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06203, 'Litueche',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06204, 'Marchihue',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06205, 'Navidad',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06206, 'Paredones',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06301, 'San Fernando',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06302, 'Chépica',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06303, 'Chimbarongo',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06304, 'Lolol',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06305, 'Nancagua',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06306, 'Palmilla',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06307, 'Peralillo',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06308, 'Placilla',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06309, 'Pumanque',6)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (06310, 'Santa Cruz',6)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07101, 'Talca',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07102, 'Constitución',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07103, 'Curepto',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07104, 'Empedrado',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07105, 'Maule',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07106, 'Pelarco',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07107, 'Pencahue',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07108, 'Río Claro',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07109, 'San Clemente',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07110, 'San Rafael',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07201, 'Cauquenes',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07202, 'Chanco',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07203, 'Pelluhue',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07301, 'Curicó',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07302, 'Hualañé',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07303, 'Licantén',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07304, 'Molina',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07305, 'Rauco',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07306, 'Romeral',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07307, 'Sagrada Familia',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07308, 'Teno',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07309, 'Vichuquén',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07401, 'Linares',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07402, 'Colbún',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07403, 'Longaví',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07404, 'Parral',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07405, 'Retiro',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07406, 'San Javier',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07407, 'Villa Alegre',7)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (07408, 'Yerbas Buenas',7)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08101, 'Concepción',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08102, 'Coronel',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08103, 'Chiguayante',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08104, 'Florida',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08105, 'Hualqui',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08106, 'Lota',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08107, 'Penco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08108, 'San Pedro de la Paz',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08109, 'Santa Juana',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08110, 'Talcahuano',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08111, 'Tomé',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08112, 'Hualpén',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08201, 'Lebu',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08202, 'Arauco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08203, 'Cañete',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08204, 'Contulmo',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08205, 'Curanilahue',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08206, 'Los Álamos',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08207, 'Tirúa',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08301, 'Los Ángeles',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08302, 'Antuco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08303, 'Cabrero',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08304, 'Laja',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08305, 'Mulchén',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08306, 'Nacimiento',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08307, 'Negrete',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08308, 'Quilaco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08309, 'Quilleco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08310, 'San Rosendo',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08311, 'Santa Bárbara',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08312, 'Tucapel',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08313, 'Yumbel',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08314, 'Alto Biobío',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08401, 'Chillán',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08402, 'Bulnes',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08403, 'Cobquecura',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08404, 'Coelemu',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08405, 'Coihueco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08406, 'Chillán Viejo',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08407, 'El Carmen',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08408, 'Ninhue',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08409, 'Ñiquén',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08410, 'Pemuco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08411, 'Pinto',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08412, 'Portezuelo',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08413, 'Quillón',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08414, 'Quirihue',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08415, 'Ránquil',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08416, 'San Carlos',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08417, 'San Fabián',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08418, 'San Ignacio',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08419, 'San Nicolás',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08420, 'Treguaco',8)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (08421, 'Yungay',8)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09101, 'Temuco',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09102, 'Carahue',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09103, 'Cunco',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09104, 'Curarrehue',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09105, 'Freire',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09106, 'Galvarino',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09107, 'Gorbea',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09108, 'Lautaro',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09109, 'Loncoche',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09110, 'Melipeuco',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09111, 'Nueva Imperial',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09112, 'Padre Las Casas',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09113, 'Perquenco',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09114, 'Pitrufquén',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09115, 'Pucón',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09116, 'Saavedra',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09117, 'Teodoro Schmidt',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09118, 'Toltén',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09119, 'Vilcún',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09120, 'Villarrica',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09121, 'Cholchol',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09201, 'Angol',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09202, 'Collipulli',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09203, 'Curacautín',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09204, 'Ercilla',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09205, 'Lonquimay',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09206, 'Los Sauces',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09207, 'Lumaco',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09208, 'Purén',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09209, 'Renaico',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09210, 'Traiguén',9)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (09211, 'Victoria',9)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14101, 'Valdivia',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14102, 'Corral',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14202, 'Futrono',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14201, 'La Unión',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14203, 'Lago Ranco',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14103, 'Lanco',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14104, 'Los Lagos',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14105, 'Máfil',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14106, 'Mariquina',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14107, 'Paillaco',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14108, 'Panguipulli',14)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (14204, 'Río Bueno',14)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10101, 'Puerto Montt',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10102, 'Calbuco',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10103, 'Cochamó',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10104, 'Fresia',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10105, 'Frutillar',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10106, 'Los Muermos',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10107, 'Llanquihue',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10108, 'Maullín',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10109, 'Puerto Varas',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10201, 'Castro',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10202, 'Ancud',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10203, 'Chonchi',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10204, 'Curaco de Vélez',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10205, 'Dalcahue',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10206, 'Puqueldón',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10207, 'Queilén',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10208, 'Quellón',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10209, 'Quemchi',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10210, 'Quinchao',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10301, 'Osorno',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10302, 'Puerto Octay',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10303, 'Purranque',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10304, 'Puyehue',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10305, 'Río Negro',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10306, 'San Juan de la Costa',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10307, 'San Pablo',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10401, 'Chaitén',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10402, 'Futaleufú',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10403, 'Hualaihué',10)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (10404, 'Palena',10)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11101, 'Coihaique',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11102, 'Lago Verde',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11201, 'Aisén',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11202, 'Cisnes',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11203, 'Guaitecas',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11301, 'Cochrane',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11302, 'O Higgins',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11303, 'Tortel',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11401 ,'Chile Chico',11)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (11402 ,'Río Ibáñez',11)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12101 ,'Punta Arenas',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12102 ,'Laguna Blanca',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12103 ,'Río Verde',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12104 ,'San Gregorio',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12201 ,'Cabo de Hornos',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12202 ,'Antártica',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12301 ,'Porvenir',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12302 ,'Primavera',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12303 ,'Timaukel',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12401 ,'Natales',12)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (12402 ,'Torres del Paine',12)

INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13101 ,'Santiago',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13102 ,'Cerrillos',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13103 ,'Cerro Navia',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13104 ,'Conchalí',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13105 ,'El Bosque',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13106 ,'Estación Central',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13107 ,'Huechuraba',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13108 ,'Independencia',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13109 ,'La Cisterna',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13110 ,'La Florida',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13111 ,'La Granja',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13112 ,'La Pintana',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13113 ,'La Reina',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13114 ,'Las Condes',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13115 ,'Lo Barnechea',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13116 ,'Lo Espejo',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13117 ,'Lo Prado',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13118 ,'Macul',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13119 ,'Maipú',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13120 ,'Ñuñoa',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13121 ,'Pedro Aguirre Cerda',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13122 ,'Peñalolén',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13123 ,'Providencia',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13124 ,'Pudahuel',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13125 ,'Quilicura',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13126 ,'Quinta Normal',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13127 ,'Recoleta',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13128 ,'Renca',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13129 ,'San Joaquín',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13130 ,'San Miguel',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13131 ,'San Ramón',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13132 ,'Vitacura',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13201 ,'Puente Alto',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13202 ,'Pirque',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13203 ,'San José de Maipo',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13301 ,'Colina',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13302 ,'Lampa',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13303 ,'Tiltil',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13401 ,'San Bernardo',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13402 ,'Buin',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13403 ,'Calera de Tango',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13404 ,'Paine',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13501 ,'Melipilla',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13502 ,'Alhué',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13503 ,'Curacaví',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13504 ,'María Pinto',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13505 ,'San Pedro',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13601 ,'Talagante',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13602 ,'El Monte',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13603 ,'Isla de Maipo' ,13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13604 ,'Padre Hurtado',13)
INSERT INTO comuna(codigo_comuna, nombre_comuna, region_comuna)VALUES (13605 ,'Peñaflor',13)

INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13320, 'CESFAM Maipo', 'CESFAM', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13333, 'CESFAM Alto Jahuel', 'CESFAM', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13390, 'CESFAM Dr. Héctor García', 'CESFAM', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13321, 'CESFAM Calera de Tango', 'CESFAM', 13403)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13334, 'CESFAM Bajos de San Agustín', 'CESFAM', 13403)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13312, 'CESFAM Dr. Carlos Lorca', 'CESFAM', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13314, 'CESFAM Cóndores Chile', 'CESFAM', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13317, 'CESFAM Santa Laura', 'CESFAM', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13323, 'CESFAM Dr. Mario Salcedo Sepúlveda', 'CESFAM', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13324, 'CESFAM Dra. Haydeé López Casoou', 'CESFAM', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13329, 'CESFAM Canciller  Orlando Letelier', 'CESFAM', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13000, 'Alter Joven', 'Centro de Salud Adolescente', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13311, 'CESFAM  Santa Anselma', 'CESFAM', 13109)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13326, 'CESFAM Eduardo Frei Montalva', 'CESFAM', 13109)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13307, 'CESFAM Padre Esteban Gumucio Vives', 'CESFAM', 13111)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13308, 'CESFAM Clara Estrella', 'CESFAM', 13116)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13309, 'CESFAM Julio Acuña Pinzón', 'CESFAM', 13116)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13310, 'CESFAM Dra. Mariela Salgado Zepeda', 'CESFAM', 13116)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13396, 'CESFAM Pueblo Lo Espejo', 'CESFAM', 13116)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13318, 'CESFAM Paine', 'CESFAM', 13404)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13319, 'CESFAM Dr. Raúl Moya Muñoz', 'CESFAM', 13404)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13303, 'CESFAM Dr. Amador Neghme', 'CESFAM', 13121)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13306, 'CESFAM Padre Pierre Dubois', 'CESFAM', 13121)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13331, 'CESFAM Edgardo Enríquez Froedden', 'CESFAM', 13121)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13313, 'CESFAM Dr. Raúl Cuevas', 'CESFAM', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13315, 'CESFAM  Confraternidad', 'CESFAM', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13316, 'CESFAM Carol Urzúa ', 'CESFAM', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13328, 'CESFAM Padre Joan Alsina', 'CESFAM', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13330, 'CESFAM Consultorio Raúl Brañes F.', 'CESFAM', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13332, 'CESFAM Juan Pablo II', 'CESFAM', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13394, 'CESFAM El Manzano', 'CESFAM', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13001, 'Rucahueche ', 'Centro de Salud Adolescente', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13301, 'CESFAM San Joaquín', 'CESFAM', 13129)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13305, 'CESFAM Dr. Arturo Baeza Goñi', 'CESFAM', 13129)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13322, 'CESFAM Sor Teresa Los Andes', 'CESFAM', 13129)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13300, 'CESFAM Barros Luco', 'CESFAM', 13130)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13302, 'CESFAM Recreo', 'CESFAM', 13130)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13402, 'PSR Linderos', 'Posta de Salud Rural', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13404, 'PSR Valdivia de Paine', 'Posta de Salud Rural', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13405, 'PSR Viluco', 'Posta de Salud Rural', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13406, 'PSR El Recurso', 'Posta de Salud Rural', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13407, 'PSR Los Morros', 'Posta de Salud Rural', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13408, 'PSR Pintué', 'Posta de Salud Rural', 13404)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13409, 'PSR Huelquén', 'Posta de Salud Rural', 13404)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13410, 'PSR Rangue', 'Posta de Salud Rural', 13404)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13411, 'PSR Abrantes', 'Posta de Salud Rural', 13404)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13412, 'PSR Chada', 'Posta de Salud Rural', 13404)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13413, 'PSR Santa Inés', 'Posta de Salud Rural', 13403)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13701, 'CECOF Yalta', 'CECOF', 13129)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13702, 'CECOF Sierra Bella', 'CECOF', 13129)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13703, 'CECOF Cooperación', 'CECOF', 13121)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13713, 'CECOF Cerrillos de Nos', 'CECOF', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13716, 'CECOF Rapa Nui', 'CECOF', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13717, 'CECOF Santa Laura', 'CECOF', 13105)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13722, 'CECOF Juan Aravena', 'CECOF', 13129)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13728, 'CECOF Lo Herrera', 'CECOF', 13401)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13753, 'CECOF Reverendo Javier Peró', 'CECOF', 13129)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13790, 'CECOF Dr. Héctor García', 'CECOF', 13402)
INSERT INTO cesfam(codigo_cesfam, nombre_cesfam, nombre_tipo_cesfam, comuna_cesfam) VALUES (13906, 'CECOF Coñimo', 'CECOF', 13129)

INSERT INTO rol(codigo_rol, nombre_rol) VALUES (1, 'Super-Usuario')
INSERT INTO rol(codigo_rol, nombre_rol) VALUES (2, 'Funcionario')
INSERT INTO rol(codigo_rol, nombre_rol) VALUES (3, 'Encargado-Programa')

INSERT INTO usuario( codigo_usuario, rut_usuario, correo_usuario, password_usuario, nombres_usuario, primer_apellido_usuario, segundo_apellido_usuario, rol_usuario, cesfam_usuario, habilitado_usuario, primer_login)VALUES (1001, '18.455.374-0', 'pablo.salinasc@usach.cl', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Pablo Javier', 'Salinas', 'Cabañas', 1, 13300, true, true)
INSERT INTO usuario( codigo_usuario, rut_usuario, correo_usuario, password_usuario, nombres_usuario, primer_apellido_usuario, segundo_apellido_usuario, rol_usuario, cesfam_usuario, habilitado_usuario, primer_login)VALUES (1002, '18.293.486-0', 'sebastian.calderon@usach.cl', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Sebastian Patricio', 'Diaz', 'Calderón', 1, 13301, true, true)
INSERT INTO usuario( codigo_usuario, rut_usuario, correo_usuario, password_usuario, nombres_usuario, primer_apellido_usuario, segundo_apellido_usuario, rol_usuario, cesfam_usuario, habilitado_usuario, primer_login)VALUES (1003, '10.234.897-2', 'veronica.dominguez@usach.cl', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Veronica', 'Dominguez', 'hola', 1, 13302, true, true)
INSERT INTO usuario( codigo_usuario, rut_usuario, correo_usuario, password_usuario, nombres_usuario, primer_apellido_usuario, segundo_apellido_usuario, rol_usuario, cesfam_usuario, habilitado_usuario, primer_login)VALUES (1005, '12.394.729-1', 'daniel.morales@usach.cl', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Daniel', 'Morales', 'Aguilera', 1, 13300, true, true)
INSERT INTO usuario( codigo_usuario, rut_usuario, correo_usuario, password_usuario, nombres_usuario, primer_apellido_usuario, segundo_apellido_usuario, rol_usuario, cesfam_usuario, habilitado_usuario, primer_login)VALUES (1006, '05.893.349-k', 'funcionario@mail.com', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'Carlos', 'Perez', 'Rodriguez', 2, 13300, true, true)

INSERT INTO estado_civil(codigo_estado_civil, nombre_estado_civil)VALUES (1, 'Soltero')
INSERT INTO estado_civil(codigo_estado_civil, nombre_estado_civil)VALUES (2, 'Casado')
INSERT INTO estado_civil(codigo_estado_civil, nombre_estado_civil)VALUES (3, 'Viudo')
INSERT INTO estado_civil(codigo_estado_civil, nombre_estado_civil)VALUES (4, 'Separado')
INSERT INTO estado_civil(codigo_estado_civil, nombre_estado_civil)VALUES (5, 'Conviviente')
INSERT INTO estado_civil(codigo_estado_civil, nombre_estado_civil)VALUES (6, 'Divorciado')
INSERT INTO estado_civil(codigo_estado_civil, nombre_estado_civil)VALUES (9, 'Desconocido')


INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (1, 'Ley 18.490 Accidentes de transporte')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (2, 'Ley 16.744 Accidentes del Trabajo y Enfermedades Profesionales')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (3, 'Ley 16.744 Accidente Escolar')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (4, 'ley 19.650/99 de Urgencia')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (5, 'PRAIS')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (6, 'Chile Solidario')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (7, 'Chile Crece Contigo')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (8, 'Otro Programa social')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (9, 'GES')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (10, 'Sin programa social')
INSERT INTO ley_social(codigo_p_social, nombre_p_social)VALUES (11, 'No Sabe/No Contesta')


INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (999, 'FONASA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (57, 'PROMEPART')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (62, 'SAN LORENZO')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (63, 'EL TENIENTE')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (65, 'CHUQUICAMATA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (66, 'CIGNA SALUD')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (67, 'COLMENA GOLDEN CROSS')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (68, 'RIO BLANCO')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (70, 'NORMEDICA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (71, 'CONSALUD')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (74, 'AETNA SALUD')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (75, 'SHELL CHILE')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (76, 'BANCO DEL ESTADO')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (78, 'ING SALUD')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (80, 'VIDA TRES')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (81, 'FERROSALUD')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (85, 'ISTEL')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (86, 'ISAMEDICA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (88, 'MAS VIDA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (89, 'CRISOL')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (94, 'CRUZ DEL NORTE')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (96, 'VIDA PLENA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (98, 'MASTER SALUD')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (99, 'BANMEDICA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (100, 'GENESIS')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (101, 'INSTSALUD')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (104, 'SFERA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (106, 'LA ARAUCANA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (107, 'CONSALUD S.A')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (1001, 'Sin previsión')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (998, 'CAPREDENA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (997, 'DIPRECA')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (1000, 'Otra')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (1003, 'Si/No sabe cuál')
INSERT INTO prevision(codigo_prevision, nombre_prevision)VALUES (1002, 'No sabe/No contesta')


INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (1, 'Alacalufe o Kawashkar')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (2, 'Atacameño')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (3, 'Aimara')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (4, 'Colla')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (5, 'Diaguita')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (6, 'Mapuche')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (7, 'Quechua')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (8, 'Rapa Nui')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (9, 'Yámana o Yagán')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (10, 'Ninguno')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (11, 'No sabe/No contesta')
INSERT INTO pueblo_originario(codigo_pueblo_originario, nombre_pueblo_originario)VALUES (12, 'Otro pueblo originario declarado')

INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (101, 'Angola')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (102, 'Argelia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (103, 'Benin')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (104, 'Botswana')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (105, 'Burkina Faso')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (106, 'Burundi')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (107, 'Cabo Verde')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (108, 'Camerún')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (109, 'Chad')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (110, 'Comores')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (111, 'Costa De Marfil')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (112, 'Djibouti')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (113, 'Egipto')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (114, 'Eritrea')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (115, 'Etiopia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (116, 'Gabón')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (117, 'Gambia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (118, 'Ghana')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (119, 'Guinea')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (120, 'Guinea - Bissau')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (121, 'Guinea Ecuatorial')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (122, 'Guinea Francesa')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (123, 'Kenia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (124, 'Lesotho')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (125, 'Liberia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (126, 'Libia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (127, 'Madagascar')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (128, 'Malawi')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (129, 'Mali')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (130, 'Marruecos')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (131, 'Mauricio')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (132, 'Mauritania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (133, 'Mayotte')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (134, 'Mozambique')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (135, 'Namibia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (136, 'Níger')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (137, 'Nigeria')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (138, 'Republica Centroafricana')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (139, 'Republica Del Congo')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (140, 'República Democrática Del Congo')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (141, 'Reunión')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (142, 'Ruanda')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (143, 'Sahara Occidental')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (144, 'Santa Elena')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (145, 'Santo Tome Y Príncipe')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (146, 'Senegal')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (147, 'Seychelles')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (148, 'Sierra Leona')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (149, 'Somalia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (150, 'Sudáfrica')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (151, 'Sudan')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (152, 'Suazilandia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (153, 'Tanzania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (154, 'Togo')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (155, 'Túnez')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (156, 'Uganda')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (157, 'Zaire')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (158, 'Zambia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (159, 'Zimbabwe')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (160, 'Sudan del Sur')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (201, 'Anguilla')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (202, 'Antigua Y Barbuda')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (203, 'Antillas Holandesas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (204, 'Argentina')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (205, 'Aruba')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (206, 'Bahamas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (207, 'Barbados')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (208, 'Belice')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (209, 'Bermudas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (210, 'Bolivia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (211, 'Brasil')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (212, 'Canadá')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (213, 'Chile')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (214, 'Colombia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (215, 'Costa Rica')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (216, 'Cuba')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (217, 'Dominica')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (218, 'Ecuador')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (219, 'El Salvador')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (220, 'Estados Unidos De América')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (221, 'Granada')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (222, 'Groenlandia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (223, 'Guadalupe')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (224, 'Guatemala')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (225, 'Guyana')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (226, 'Guyana Francesa')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (227, 'Haití')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (228, 'Honduras')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (229, 'Islas Caimán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (230, 'Islas Georgia Del Sur')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (231, 'Islas Malvinas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (232, 'Islas Turcos Y Caicos')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (233, 'Islas Vírgenes Americanas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (234, 'Islas Vírgenes Británicas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (235, 'Jamaica')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (236, 'Martinica')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (237, 'México')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (238, 'Monserrat')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (239, 'Nicaragua')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (240, 'Panamá')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (241, 'Paraguay')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (242, 'Perú')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (243, 'Puerto Rico')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (244, 'Republica Dominicana')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (245, 'San Cristóbal Y Nevis')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (246, 'San Pedro Y Miquelón')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (247, 'San Vicente Y Las Granadinas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (248, 'Santa Lucia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (249, 'Surinam')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (250, 'Trinidad Y Tobago')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (251, 'Uruguay')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (252, 'Venezuela')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (301, 'Afganistán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (302, 'Arabia Saudita')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (303, 'Armenia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (304, 'Azerbaiyán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (305, 'Bahréin')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (306, 'Bangladesh')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (307, 'Bután')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (308, 'Birmania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (309, 'Brunei')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (310, 'Camboya')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (311, 'China')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (312, 'Emiratos Árabes Unidos')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (313, 'Filipinas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (314, 'Georgia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (315, 'Hong Kong')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (316, 'India')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (317, 'Indonesia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (318, 'Irak')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (319, 'Irán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (320, 'Israel')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (321, 'Japón')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (322, 'Jordania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (323, 'Kazajstán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (324, 'Kirguizistán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (325, 'Kuwait')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (326, 'Laos')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (327, 'Líbano')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (328, 'Macao')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (329, 'Malasia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (330, 'Maldivas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (331, 'Mongolia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (332, 'Nepal')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (333, 'Omán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (334, 'Pakistán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (335, 'Palestina')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (336, 'Qatar')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (337, 'Republica De Corea')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (338, 'Republica Democrática Popular De Corea')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (339, 'Rusia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (340, 'Singapur')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (341, 'Siria')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (342, 'Sri Lanka')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (343, 'Tailandia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (344, 'Taiwán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (345, 'Tayikistán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (346, 'Turkmenistán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (347, 'Turquía')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (348, 'Uzbekistán')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (349, 'Vietnam')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (350, 'Yemen')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (401, 'Albania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (402, 'Alemania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (403, 'Andorra')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (404, 'Austria')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (405, 'Bélgica')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (406, 'Bielorrusia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (407, 'Bosnia - Herzegovina')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (408, 'Bulgaria')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (409, 'Chipre')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (410, 'Croacia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (411, 'Dinamarca')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (412, 'Eslovaquia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (413, 'Eslovenia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (414, 'España')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (415, 'Estonia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (416, 'Finlandia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (417, 'Francia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (418, 'Gibraltar')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (419, 'Grecia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (420, 'Holanda')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (421, 'Hungría')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (422, 'Irlanda')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (423, 'Islandia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (424, 'Islas Feroe')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (425, 'Italia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (426, 'Letonia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (427, 'Liechtenstein')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (428, 'Lituania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (429, 'Luxemburgo')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (430, 'Macedonia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (431, 'Malta')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (432, 'Mónaco')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (433, 'Noruega')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (434, 'Polonia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (435, 'Portugal')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (436, 'Reino Unido')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (437, 'Republica Checa')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (438, 'Republica De Moldavia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (439, 'Rumania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (440, 'San Marino')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (441, 'Suecia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (442, 'Suiza')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (443, 'Ucrania')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (444, 'Vaticano')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (445, 'Yugoslavia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (501, 'Ashmore Y Cartier')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (502, 'Australia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (503, 'Christmas')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (504, 'Estados Federados De Micronesia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (505, 'Fiji')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (506, 'Guam')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (507, 'Isla Kingman Reef')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (508, 'Isla Lord Howe')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (509, 'Isla Norfolk')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (510, 'Isla Palmyra')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (511, 'Isla Wake')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (512, 'Islas Cocos')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (513, 'Islas Cook')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (514, 'Islas Jarvis')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (515, 'Islas Johnston')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (516, 'Islas Mariana Del Norte')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (517, 'Islas Marshall')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (518, 'Islas Midway')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (519, 'Islas Salomón')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (520, 'Islas Wallis Y Futuna')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (521, 'Kiribati')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (522, 'Macquarie')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (523, 'Nauru')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (524, 'Niue')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (525, 'Nueva Caledonia')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (526, 'Nueva Zelanda')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (527, 'Palau')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (528, 'Papúa - Nueva Guinea')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (529, 'Pitcairn')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (530, 'Polinesia Francesa')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (531, 'Samoa Occidental')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (532, 'Samoa Oriental')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (533, 'Tokelau')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (534, 'Tonga')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (535, 'Tuvalu')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (536, 'Vanuatu')
INSERT INTO nacionalidad(codigo_nacionalidad, nombre_nacionalidad)VALUES (999, 'Otros')
INSERT INTO parametros(ruta_parametros, tamano_imagen_parametros) VALUES ('C:/genogramas', 5)
--INSERT INTO parametros(ruta_parametros) VALUES ('/opt/genograma')
--INSERT INTO parametros(ruta_parametros) VALUES ('/home/seba/genogramas')